---
- name: "Moduli: Generate candidates"
  command: ssh-keygen -G {{ ssh_server_moduli_path }}/moduli-candidates -b {{ ssh_server_moduli_bits }}
  args:
    creates: "{{ ssh_server_moduli_path }}/moduli-candidates"
  delegate_to: localhost
  become: no

- name: "Moduli: Test candidates"
  command: ssh-keygen -T {{ ssh_server_moduli_path }}/moduli -f {{ ssh_server_moduli_path }}/moduli-candidates
  args:
    creates: "{{ ssh_server_moduli_path }}/moduli"
  delegate_to: localhost
  become: no

- name: "Moduli: Copy file"
  copy:
    src: "{{ ssh_server_moduli_path }}/moduli"
    dest: /etc/ssh/moduli
    owner: root
    group: root
    mode: '0444'
  notify: restart sshd
