---
- name: Generate ssh-keygen command for the remote SSH version
  set_fact:
    ssh_keygen_extra_params: "{% if not ssh_legacy %}-o -a {{ ssh_keygen_iterations }}{% endif %}"

- name: Ensure Keys directory
  file:
    path: "{{ ssh_keygen_keys_path }}"
    mode: '0700'
    state: directory
  delegate_to: localhost
  become: no

- name: Ensure User Keys directory
  file:
    path: "{{ ssh_keygen_user_keys_path }}"
    mode: '0700'
    state: directory
  delegate_to: localhost
  become: no

- name: Ensure custom User Keys directories
  file:
    path: "{{ ssh_server_user_ca.value.path }}"
    mode: '0700'
    state: directory
  delegate_to: localhost
  with_dict: "{{ ssh_server_user_cas }}"
  loop_control:
    loop_var: ssh_server_user_ca
    label: "{{ ssh_server_user_ca.key }}"
  when: ssh_server_user_cas | length > 0 and ssh_server_user_ca.value.path is defined

- name: Ensure Certificate Authority Keys directory
  file:
    path: "{{ ssh_ca_path }}"
    mode: '0700'
    state: directory
  delegate_to: localhost
  become: no
