---
- name: "{{ key_user_ca }}: Generate User Certificate Authority key pair"
  command: ssh-keygen {{ extra_params }} -t rsa -b {{ key_bits }} -N '{{ key_passphrase }}' -C 'User Certificate Authority {{ key_user_ca }}' -f {{ key_path }}/{{ key_file }}
  args:
    creates: "{{ key_path }}/{{ key_file }}"
  delegate_to: localhost
  become: no

- name: "{{ key_user_ca }}: Load User Certificate Authority public key"
  set_fact:
    ssh_server_user_ca_keys: "{{ ssh_server_user_ca_keys }} + ['{{ lookup('file', key_path + '/' + key_file + '.pub') }}']"
