---
- include_tasks: ssh-server-moduli.yml
  when: ssh_server_regenerate_moduli

- include_tasks: ssh-keys-common.yml

- include_tasks: ssh-server-keys.yml
  when: ssh_server_regenerate_keys

- include_tasks: ssh-server-user-keys.yml
  when: ssh_server_regenerate_user_keys

- include_tasks: ssh-server-revoke-user-keys.yml
  when: ssh_server_regenerate_revoked_keys

- name: Create SSH server banner
  copy:
    dest: "{{ ssh_server_banner_path }}"
    content: "{{ ssh_server_banner }}"
    owner: root
    group: root
    mode: '0600'
  when: ssh_server_banner | length > 0

- name: Verify Trusted User CA Keys existence
  stat:
    path: /etc/ssh/trusted_user_ca_keys
  register: ssh_server_trusted_user_ca_keys_exists

- name: Verify Revoked Keys existence
  stat:
    path: /etc/ssh/revoked_keys
  register: ssh_server_revoked_keys_exists

- name: Add SSH server config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -T -f %s
  notify: restart sshd
